### PR TITLE
Improved prepared statement related functions.

### PR DESCRIPTION
**Pull request by shawnw**
- Added functions to iterate and fold over result rows
- Added functions for easier binding of non-64-bit integer values,
  named parameters, and multiple values all at once.
- Similar for getting integer result column values..
- Support blobs as byte sequences as an alternative to strings.

Basically, a bunch of stuff to make it easier to use prepared statements.

### CODE REVIEW

**Comment by tspence** [comment]
@shawnw I'm interested in standardizing the type conversion code.  Can we consolidate this with https://github.com/mmottl/sqlite3-ocaml/pull/39 ?

**Comment by shawnw** [comment]
@tspence What did you have in mind?

**Comment by mmottl** [comment]
@shawnw I've just merged #39 by @tspence.  I haven't made a release yet so you may want to weigh in on the changes and maybe suggest new ones.  If required, could you please update this pull request to the current development branch?

**Comment by mmottl** [comment]
@shawnw Could you please let me know whether you'd be fine with a new major release that does not yet contain your pull request?  Ideally, I'd only want to change APIs once, but if you need more time and don't think your changes would break the API about to be released, I'll make a new release.

**Comment by shawnw** [comment]
I still don't understand what the issue is between this PR and that other one. That one seems to have yet another way to avoid having to explicitly construct variants, but it's also a bit more awkward to use and also doesn't seem to conflict with that part of mine. Would you rather each bit be split up into its own PR or something?

**Comment by mmottl** [comment]
I've significantly rewritten parts of the API, mostly `bind` and `column`-related functions.  In particular, they now access the specialized functions already in the SQLite3 C-library.  This should make it easier to understand their behavior.  Please feel free to comment on these changes before I make the next release.

**Pull request merged**
