### PR TITLE
Add brew checking capability during build

### PR DESCRIPTION
**Pull request by rleonid**
The problem: The default Sqlite3 library installed on MacOSX is not compiled with some useful extensions. Consequently, some users install a version via [homebrew](https://github.com/Homebrew/homebrew), but linking against that library specifically requires tweaking where `pkg-config` looks for the appropriate flags. My previous [attempt](https://github.com/mmottl/sqlite3-ocaml/commit/967198e2b9adb38844d296d1f6b0803d25d04006) to solve this problem violated the default expected behavior of `pkg-config`.

Proposal:
This patch enables a flag in the `sqlite3-ocaml` build logic to perform a check for a `brewed` sqlite3 and link against it specifically. 
Furthermore adding

```
["ocaml" "setup.ml" "-configure" "--prefix" prefix "%{sqlite3:brewcheck}%"]
```
to this packages `opam` would allow a downstream installer to say
```
$OPAMVAR_sqlite3_brewcheck=--enable-brewcheck opam install sqlite3 
```
when they use sqlite3.

### CODE REVIEW

**Comment by rleonid** [comment]
If you are not interested in adding this very configuration specific change to the build change, perhaps this patch would be acceptable as an `opam` patch?

**Comment by mmottl** [comment]
Since this flag has to be explicitly turned on to change the build process, I don't mind adding it to the distribution if it solves your problem.  There is an `eprintf` statement in the code that may be left over from debugging, because the message is not very helpful.  You may want to remove it or change the message if it serves a purpose.  I'll merge the patch then.  I haven't tested it though, because I don't use homebrew so I'll trust that it works for you.

**Comment by rleonid** [comment]
Thanks for the quick check and turn around. This would make it easier to write one install command for our libraries.

I've tested the patch on an os-x with brew. But I haven't tried in on a Linux box which caused the error last time, but I doubt that bash syntax would be different. The only error is if a user enables this option without having `brew` (or `grep` too) installed, but then the `Unix.open_process_in` can't read from stdout and returns `[]` (error gets written to stderr).

I know that this wasn't @ygrek 's preferred solution, but since this library is so critical to a lot of applications maybe he can chime in if this is acceptable and doesn't cause any conflicts with his uses.

**Comment by mmottl** [comment]
I'm quite pragmatic when it comes to supporting compatibility.  As long as other people's installation isn't broken, I'm fine with adding features that make life easier with certain configurations.  Lets see whether @ygrek has another proposal, otherwise I'll merge.

**Comment by ygrek** [comment]
I find it unfortunate that the fix is in the library and not in the platform, but as long as it doesn't break my builds (on linux) - I am fine

**Comment by mmottl** [comment]
Ok, I've merged.  We don't live in an ideal world so lets make it incrementally better...

**Comment by mmottl** [comment]
@rleonid I've just had a short discussion with @Chris00 by email on what we can do about special configuration situations in packages.  It seems that going through the package manager doesn't really make things easier, because it can't do much more with configuration flags than pass them along.

I'm not sure whether we should get rid of the flag in the Oasis file.  I guess it can stay as a configuration alternative for people that compile the package manually.  But maybe you could add a little code (+ corresponding documentation in the README) that checks for the presence of an environment variable (maybe `SQLITE3_OCAML_BREWCHECK`)?  That way users could configure the package whether OPAM is used for package management or something else.

**Pull request merged**
